chore(package.json): update dependencies
nirdhara/nirdhara pull request #2
Opened 2023-09-14 19:24 UTC by gowravshekar

2023-09-15 16:34 UTC, akkdodev requested changes

2023-09-15 16:34 UTC, akkdodev commented on apps/composer-api/package.json
@gowravshekar 

Command : __OPEN_API__=true yarn start

Error : [
<img width="1497" alt="Screenshot 2023-09-15 at 1 26 40 AM" src="https://github.com/nirdhara/nirdhara/assets/144836106/f69fe9b7-1b7b-4052-b0ce-47886e7d5cc4">
](url)

2023-09-17 16:56 UTC, gowravshekar commented on apps/composer-api/package.json
@akkdodev, swagger issue is resolved.

2023-09-18 09:23 UTC, akkdodev approved these changes

2023-09-18 09:28 UTC, akkdodev commented
composer-api : application is starting properly with swagger.
composer-ui : application is starting properly.

2023-09-18 09:29 UTC, merged